Force install bunder
This avoids errors like:

$ gem install --bindir /usr/local/bin bundler -v "$INSTALL_BUNDLER_VERSION"
ERROR:  Error installing bundler:
	"bundle" from bundler conflicts with /usr/local/bin/bundle